version: '3.4'

services:
  farkserverworker:
    image: farkserverworker:dev
    container_name: FarkServerWorker
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "FarkServerWorker"
    #environment:
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_farkserverworker$
    volumes:
      - C:\Users\renan.medeiros\source\repos\FarkWebServerTeste\FarkServerWorker:/app
      - C:\Users\renan.medeiros\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_farkserverworker$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_farkserverworker$ \"/app/bin/Debug/netcoreapp3.1/FarkServerWorker.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true